global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aerospike'
    static_configs:
        - targets: ['exporter:9145']

  - job_name: 'kafka'
    static_configs:
        - targets: ['kafka-exporter:9308']
